"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import PageHeader from "@/features/doctor/components/PageHeader";
import { appointmentService } from "@/services/appointmentService";
import type { DoctorSession, DoctorSessionInput } from "@/types/appointment";

const blank: DoctorSessionInput = { hospitalId:"healthbridge-hospital",hospitalName:"HealthBridge Hospital",specializationName:"",sessionDate:"",startTime:"",endTime:"",maxAppointments:10,notes:"" };
export default function DoctorSchedulePage() {
  const [sessions,setSessions]=useState<DoctorSession[]>([]); const [form,setForm]=useState<DoctorSessionInput>(blank); const [editing,setEditing]=useState<string|null>(null); const [showForm,setShowForm]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async()=>{try{setLoading(true);setSessions(await appointmentService.getMySessions());}catch(e){setError(e instanceof Error?e.message:"Unable to load sessions.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const change=<K extends keyof DoctorSessionInput>(key:K,value:DoctorSessionInput[K])=>setForm(current=>({...current,[key]:value}));
  const submit=async(e:FormEvent)=>{e.preventDefault();try{setSaving(true);setError("");if(editing)await appointmentService.updateSession(editing,form);else await appointmentService.createSession(form);setForm(blank);setEditing(null);setShowForm(false);await load();}catch(err){setError(err instanceof Error?err.message:"Unable to save session.");}finally{setSaving(false);}};
  const edit=(s:DoctorSession)=>{setEditing(s.sessionId);setForm({hospitalId:s.hospitalId,hospitalName:s.hospitalName,specializationId:s.specializationId,specializationName:s.specialization,sessionDate:s.sessionDate,startTime:s.startTime,endTime:s.endTime??"",maxAppointments:s.maxAppointments,notes:s.notes??""});setShowForm(true);};
  const status=async(id:string,next:"HOLIDAY"|"CANCELLED")=>{try{await appointmentService.updateSessionStatus(id,next);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update session.");}};
  return <div className="space-y-6"><PageHeader eyebrow="Doctor channeling" title="Sessions & schedule" description="Create capacity-based sessions and manage your future channeling schedule." />
    <div className="flex justify-end"><button onClick={()=>{setEditing(null);setForm(blank);setShowForm(v=>!v);}} className="rounded-xl bg-teal-600 px-5 py-3 text-sm font-semibold text-white">{showForm?"Close":"Create Session"}</button></div>
    {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
    {showForm&&<form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center"><h2 className="text-lg font-bold">{editing?"Edit session":"New doctor session"}</h2><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-700">HealthBridge Hospital</span></div><p className="mt-2 text-sm text-slate-500">All sessions are automatically assigned to HealthBridge Hospital.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Input label="Specialization *" value={form.specializationName} onChange={v=>change("specializationName",v)}/><Input label="Date *" type="date" min={new Date().toISOString().slice(0,10)} value={form.sessionDate} onChange={v=>change("sessionDate",v)}/><Input label="Start Time *" type="time" value={form.startTime} onChange={v=>change("startTime",v)}/><Input label="End Time" type="time" value={form.endTime??""} onChange={v=>change("endTime",v)}/><Input label="Maximum Appointments *" type="number" min="1" value={String(form.maxAppointments)} onChange={v=>change("maxAppointments",Number(v))}/><Input label="Notes" value={form.notes??""} onChange={v=>change("notes",v)}/></div><div className="mt-5 flex justify-end"><button disabled={saving} className="rounded-xl bg-teal-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving?"Saving...":editing?"Save Changes":"Create Session"}</button></div></form>}
    {loading?<div className="rounded-2xl border bg-white p-10 text-center text-sm text-slate-500">Loading sessions...</div>:sessions.length===0?<div className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500">No sessions created yet.</div>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Date","Time","Hospital","Capacity","Remaining","Status","Actions"].map(h=><th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{sessions.map(s=><tr key={s.sessionId}><td className="px-5 py-4 font-semibold">{s.sessionDate}<span className="block text-xs font-normal text-slate-400">{s.dayOfWeek}</span></td><td className="px-5 py-4">{s.startTime}{s.endTime?` – ${s.endTime}`:""}</td><td className="px-5 py-4">{s.hospitalName}</td><td className="px-5 py-4 font-semibold">{s.activeAppointments} / {s.maxAppointments} Booked</td><td className="px-5 py-4">{s.remainingAppointments}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{s.status}</span></td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><Link href={`/doctor/sessions/${s.sessionId}/queue`} className="font-semibold text-teal-700">View Queue</Link><button onClick={()=>edit(s)} className="font-semibold text-blue-700">Edit</button><button onClick={()=>void status(s.sessionId,"HOLIDAY")} className="font-semibold text-amber-700">Mark Holiday</button><button onClick={()=>void status(s.sessionId,"CANCELLED")} className="font-semibold text-rose-700">Cancel</button></div></td></tr>)}</tbody></table></div>}
  </div>;
}
function Input({label,value,onChange,type="text",min}:{label:string;value:string;onChange:(value:string)=>void;type?:string;min?:string}){return <label className="space-y-2"><span className="text-sm font-medium text-slate-700">{label}</span><input required={label.includes("*")} type={type} min={min} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-teal-500"/></label>}
