"use client";

import { useEffect, useState } from "react";
import { Download } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import FraudDetectionTabs from "@/components/fraud-detection/FraudDetectionTabs";
import { fraudDetectionService, type FraudRecord } from "@/services/fraudDetectionService";

const text = (record: FraudRecord | undefined, ...keys: string[]) => { const key = keys.find((item) => record?.[item] !== undefined && record[key] !== null); return key ? String(record?.[key]) : "-"; };

export default function FraudReportsPage() {
  const [statistics, setStatistics] = useState<FraudRecord>();
  const [riskStatistics, setRiskStatistics] = useState<FraudRecord>();
  const [alerts, setAlerts] = useState<FraudRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([fraudDetectionService.getAlertStatistics(), fraudDetectionService.getRiskScoreStatistics(), fraudDetectionService.getRecentAlerts()]).then(([alertStats, scoreStats, recent]) => { setStatistics(alertStats); setRiskStatistics(scoreStats); setAlerts(recent.items); }).catch(() => setError("Fraud report data is unavailable.")).finally(() => setLoading(false)); }, []);
  const download = () => { const lines = ["Fraud Detection Intelligence Report", ...Object.entries(statistics ?? {}).map(([key, value]) => `${key}: ${String(value)}`), "", "Risk score statistics", ...Object.entries(riskStatistics ?? {}).map(([key, value]) => `${key}: ${String(value)}`), "", "Recent alerts", ...alerts.map((alert) => `${text(alert, "claimId", "id")} ${text(alert, "title", "alertType")} ${text(alert, "severity", "riskLevel", "risk")}`)]; const blob = new Blob([lines.join("\n")], { type: "text/plain" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "health-bridge-fraud-report.txt"; link.click(); URL.revokeObjectURL(url); };
  return <DashboardLayout pageTitle="Insurance" userRole="INSURANCE_OFFICER"><div className="min-h-screen bg-[#fbfcfd] px-4 py-6 text-[#16191d] sm:px-7 lg:px-10 lg:py-9"><div className="mx-auto max-w-7xl"><FraudDetectionTabs /><header className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#6c7680]">Claims intelligence</p><h1 className="text-[28px] font-semibold sm:text-[32px]">Fraud reports</h1><p className="mt-1 text-sm text-[#7b838c]">Export summaries generated from live fraud endpoints.</p></div><button type="button" onClick={download} disabled={loading || Boolean(error)} className="inline-flex items-center gap-2 rounded-lg bg-[#1769e8] px-4 py-2 text-xs font-medium text-white disabled:opacity-60"><Download className="h-3.5 w-3.5" /> Download report</button></header>{loading && <div role="status" className="rounded-2xl border bg-white p-8 text-center text-sm text-[#707981]">Loading report data...</div>}{error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center text-sm text-red-700">{error}</div>}{!loading && !error && <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-[#e7e9ec] bg-white p-5 sm:p-6"><h2 className="text-sm font-semibold">Alert statistics</h2><div className="mt-5 space-y-3 text-xs">{Object.entries(statistics ?? {}).map(([key, value]) => <div key={key} className="flex justify-between border-b border-[#edf0f2] pb-2"><span className="text-[#65707a]">{key}</span><strong>{String(value)}</strong></div>)}</div></article><article className="rounded-2xl border border-[#e7e9ec] bg-white p-5 sm:p-6"><h2 className="text-sm font-semibold">Risk score statistics</h2><div className="mt-5 space-y-3 text-xs">{Object.entries(riskStatistics ?? {}).map(([key, value]) => <div key={key} className="flex justify-between border-b border-[#edf0f2] pb-2"><span className="text-[#65707a]">{key}</span><strong>{String(value)}</strong></div>)}</div></article><article className="rounded-2xl border border-[#e7e9ec] bg-white p-5 sm:p-6 lg:col-span-2"><h2 className="text-sm font-semibold">Recent alerts included</h2>{alerts.length === 0 ? <p className="mt-4 text-sm text-[#9299a0]">No recent fraud alerts returned.</p> : <div className="mt-4 divide-y divide-[#edf0f2]">{alerts.map((alert, index) => <div key={index} className="flex justify-between py-3 text-xs"><span>{text(alert, "claimId", "id")} · {text(alert, "title", "alertType", "ruleName")}</span><span>{text(alert, "severity", "riskLevel", "risk")}</span></div>)}</div>}</article></section>}</div></div></DashboardLayout>;
}
