"use client";

import { useParams } from "next/navigation";
import { useCallback,useEffect,useState } from "react";
import { appointmentService } from "@/services/appointmentService";
import type { Appointment,DoctorSession } from "@/types/appointment";

export default function DoctorQueuePage(){
  const{sessionId}=useParams<{sessionId:string}>();const[session,setSession]=useState<DoctorSession|null>(null);const[queue,setQueue]=useState<Appointment[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{setLoading(true);setError("");const[s,q]=await Promise.all([appointmentService.getSession(sessionId),appointmentService.getQueue(sessionId)]);setSession(s);setQueue(q);}catch(e){setError(e instanceof Error?e.message:"Unable to load queue.");}finally{setLoading(false);}},[sessionId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const move=async(action:"start"|"previous"|"next")=>{try{setSession(await appointmentService.updateCurrentQueue(sessionId,action));}catch(e){setError(e instanceof Error?e.message:"Unable to update number.");}};
  const mark=async(id:string,status:"COMPLETED"|"NO_SHOW")=>{try{await appointmentService.updateAppointmentQueueStatus(id,status);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update appointment.");}};
  if(loading)return <div className="rounded-2xl border bg-white p-10 text-center text-slate-500">Loading session queue...</div>;
  return <div className="space-y-6">{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error}</div>}{session&&<><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Doctor session</p><div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-2xl font-bold">{session.sessionDate} at {session.startTime}</h1><p className="mt-1 text-sm text-slate-500">{session.hospitalName} · {session.specialization} · {session.activeAppointments}/{session.maxAppointments} booked</p></div><div className="rounded-2xl bg-teal-50 px-8 py-5 text-center"><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Current Number</p><p className="mt-1 text-5xl font-black text-teal-800">{String(session.currentQueueNumber).padStart(2,"0")}</p></div></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>void move("start")} className="rounded-xl bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Start Queue</button><button onClick={()=>void move("previous")} className="rounded-xl border px-4 py-2 text-sm font-semibold">Previous</button><button onClick={()=>void move("next")} className="rounded-xl border px-4 py-2 text-sm font-semibold">Next</button></div></section>
    <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Appointment No.</th><th className="px-5 py-4">Patient Name</th><th className="px-5 py-4">Reference</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{queue.map(a=><tr key={a.appointmentId}><td className="px-5 py-4 text-xl font-black text-teal-700">{String(a.appointmentNumber).padStart(2,"0")}</td><td className="px-5 py-4 font-semibold">{a.patientName}</td><td className="px-5 py-4">{a.referenceNumber}</td><td className="px-5 py-4">{a.status}</td><td className="px-5 py-4">{["BOOKED","UPCOMING"].includes(a.status)&&<div className="flex gap-3"><button onClick={()=>void mark(a.appointmentId,"COMPLETED")} className="font-semibold text-emerald-700">Complete</button><button onClick={()=>void mark(a.appointmentId,"NO_SHOW")} className="font-semibold text-rose-700">No show</button></div>}</td></tr>)}{queue.length===0&&<tr><td colSpan={5} className="p-10 text-center text-slate-500">No patients booked for this session.</td></tr>}</tbody></table></section></>}</div>;
}
