import Link from "next/link";
import { ArrowLeft, CheckCircle2, FileSearch, Flag, ShieldAlert } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import FraudDetectionTabs from "@/components/fraud-detection/FraudDetectionTabs";

const evidence = [
  { label: "Duplicate service code", value: "2 matching submissions", status: "Critical", color: "text-[#ef1624]", bg: "bg-[#fff0f1]" },
  { label: "Provider history", value: "3 prior warnings", status: "Review", color: "text-[#e88900]", bg: "bg-[#fff7e8]" },
  { label: "Patient eligibility", value: "Coverage confirmed", status: "Clear", color: "text-[#00a979]", bg: "bg-[#e8fbf4]" },
];

const timeline = [
  { time: "12 Aug · 09:42", title: "Claim submitted", detail: "BlueCross submitted CLM-20481 for outpatient imaging." },
  { time: "12 Aug · 09:44", title: "Rule triggered", detail: "Duplicate billing rule matched an earlier service code." },
  { time: "12 Aug · 10:06", title: "Assigned to analyst", detail: "Case routed to the insurance investigation queue." },
];

export default function ClaimAnalysisPage() {
  return <DashboardLayout pageTitle="Insurance" userRole="INSURANCE_OFFICER"><div className="min-h-screen bg-[#fbfcfd] px-4 py-6 text-[#16191d] sm:px-7 lg:px-10 lg:py-9"><div className="mx-auto max-w-[1280px]"><FraudDetectionTabs /><div className="mb-5"><Link href="/fraud-detection/alerts" className="inline-flex items-center gap-2 text-[11px] font-medium text-[#6c7680] hover:text-[#1769e8]"><ArrowLeft className="h-3.5 w-3.5" /> Back to alerts</Link></div><header className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#6c7680]">Investigation workspace</p><h1 className="text-[28px] font-semibold tracking-[-0.04em] text-[#171a1e] sm:text-[32px]">Claim analysis</h1><p className="mt-1 text-sm text-[#7b838c]">Inspect evidence and decide the next action for a flagged claim.</p></div><div className="flex gap-2"><button type="button" className="rounded-lg border border-[#e4e7ea] bg-white px-3 py-2 text-[11px] font-medium text-[#414850]">Save note</button><button type="button" className="inline-flex items-center gap-2 rounded-lg bg-[#ef1624] px-3 py-2 text-[11px] font-medium text-white"><Flag className="h-3.5 w-3.5" /> Escalate claim</button></div></header>

<section className="mb-5 grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,0.85fr)]"><article className="rounded-2xl border border-[#e7e9ec] bg-white p-5 shadow-[0_2px_10px_rgba(26,36,44,0.02)] sm:p-6"><div className="mb-6 flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-[#20252a]">CLM-20481</h2><span className="rounded-full bg-[#fff0f1] px-2 py-1 text-[10px] font-medium text-[#ef1624]">High risk</span></div><p className="mt-1 text-[11px] text-[#9299a0]">Ava Thompson · BlueCross · Submitted 12 Aug 2026</p></div><FileSearch className="h-5 w-5 text-[#398bff]" /></div><div className="grid gap-3 sm:grid-cols-2">{[{ label: "Billed amount", value: "$4,860.00" }, { label: "Service date", value: "11 Aug 2026" }, { label: "Procedure", value: "MRI - outpatient" }, { label: "Assigned analyst", value: "Unassigned" }].map((item) => <div key={item.label} className="rounded-xl bg-[#fafbfc] px-4 py-3"><p className="text-[10px] text-[#9299a0]">{item.label}</p><p className="mt-1 text-sm font-medium text-[#30373d]">{item.value}</p></div>)}</div></article><article className="rounded-2xl border border-[#e7e9ec] bg-white p-5 shadow-[0_2px_10px_rgba(26,36,44,0.02)] sm:p-6"><div className="flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-[#ef1624]" /><h2 className="text-sm font-semibold text-[#20252a]">Risk score</h2></div><p className="mt-5 text-[42px] font-semibold leading-none tracking-[-0.05em] text-[#ef1624]">91<span className="text-lg text-[#9ca3a9]">/100</span></p><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#f0f1f2]"><div className="h-full w-[91%] rounded-full bg-[#ef1624]" /></div><p className="mt-3 text-[11px] leading-5 text-[#7b838c]">Duplicate billing and provider history account for most of this score.</p></article></section>

<section className="grid gap-4 xl:grid-cols-[minmax(0,1.15fr)_minmax(320px,0.85fr)]"><article className="rounded-2xl border border-[#e7e9ec] bg-white p-5 shadow-[0_2px_10px_rgba(26,36,44,0.02)] sm:p-6"><h2 className="text-sm font-semibold text-[#20252a]">Evidence summary</h2><p className="mt-1 text-[11px] text-[#9299a0]">Signals used to calculate the risk score</p><div className="mt-5 space-y-3">{evidence.map((item) => <div key={item.label} className="flex items-center justify-between gap-3 rounded-xl border border-[#edf0f2] px-4 py-3"><div><p className="text-xs font-medium text-[#30373d]">{item.label}</p><p className="mt-1 text-[10px] text-[#9299a0]">{item.value}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${item.bg} ${item.color}`}>{item.status}</span></div>)}</div></article><article className="rounded-2xl border border-[#e7e9ec] bg-white p-5 shadow-[0_2px_10px_rgba(26,36,44,0.02)] sm:p-6"><h2 className="text-sm font-semibold text-[#20252a]">Case timeline</h2><div className="mt-5 space-y-5">{timeline.map((item, index) => <div key={item.time} className="relative flex gap-3"><div className="relative flex w-4 justify-center"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${index === timeline.length - 1 ? "bg-[#398bff]" : "bg-[#cbd2d8]"}`} />{index < timeline.length - 1 && <span className="absolute top-4 h-8 w-px bg-[#e4e7ea]" />}</div><div><p className="text-[10px] text-[#9299a0]">{item.time}</p><p className="mt-1 text-xs font-medium text-[#30373d]">{item.title}</p><p className="mt-1 text-[10px] leading-4 text-[#7b838c]">{item.detail}</p></div></div>)}</div><div className="mt-6 flex items-center gap-2 rounded-xl bg-[#e8fbf4] px-3 py-3 text-[10px] text-[#008b65]"><CheckCircle2 className="h-4 w-4" /> Eligibility checks completed successfully.</div></article></section></div></div></DashboardLayout>;
}
